ecommercesite/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('',views.cart_detail,name='cart_detail'),
	path('<int:productid>/',views.cart_add,name='cart_add'),
	path('remove/<int:productid>/',views.cart_remove,name='cart_remove'),
    path('home',views.home,name='home'),
]

ecommercesite/ecommercesite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls')),
     path('',include('products.urls')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

ecommercesite/products/urls.py
from django.urls import path,include
from. import views



urlpatterns = [
   path('',views.home,name="hm"),
   path('product/<int:productid>',views.product,name="pr"),
   path('Samsung',views.samsung,name="samsung"),
   path('Huawei',views.huawei,name="hwawei"),
   path('Apple',views.Apple,name="Apple"),
   path('cart',views.cart,name="category"),
]

ecommercesite/cart/models.py
from django.db import models

# Create your models here.

ecommercesite/products/models.py
from statistics import mode
from unicodedata import name
from django.db import models




class Category(models.Model):

     name= models.CharField(max_length=100)
     description= models.TextField()
     
     def __str__(self):
         return self.name

     
    



class Product(models.Model):
    name= models.CharField(max_length=100)
    description= models.TextField()
    image=models.ImageField()
    price=models.DecimalField(max_digits=11,decimal_places=2)
    category_id=models.ForeignKey(Category,on_delete=models.CASCADE)

    def str(self):
        return self.name


class cart(models.Model):

    name= models.CharField(max_length=100)
    description= models.TextField()
    image=models.ImageField()
    price=models.DecimalField(max_digits=11,decimal_places=2)
    category_id=models.ForeignKey(Category,on_delete=models.CASCADE)

    def str(self):
        return self.name
        

ecommercesite/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]


class CartAddProductForm(forms.Form):
    # TODO: Define form fields here
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

ecommercesite/cart/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request,productid):
	cart = Cart(request)
	product = get_object_or_404(Product,id=productid)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(
			product=product,
			quantity=cd['quantity'],
			update_quantity=cd['update']
			)
	return redirect('cart:cart_detail')

def cart_remove(request,productid):
	cart = Cart(request)
	product = get_object_or_404(Product,id=productid)
	cart.remove(product)
	return redirect('cart:cart_detail')

def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'],'update':True})
	context = {
		'cart':cart
	}
	return render(request,'cart/detail.html',context)


def home (request):
    return render (request,'pages/homepage.html',{
        'all': Product.objects.order_by('-id'),

    })

ecommercesite/products/views.py
from unicodedata import category
from django.shortcuts import render
from .models import Product
from .models import Category
from .models import cart
from cart.forms import CartAddProductForm
# Create your views here.
def home (request):
    return render (request,'pages/homepage.html',{
        'all': Product.objects.order_by('-id'),

    })

def cart (request):
    cart1= Product.objects.all()
    Cart=cart()
    Cart.name= cart1.name
    Cart.image= cart1.image
    Cart.description= cart1.description
    Cart.price= cart1.price
    Cart.save()
    rows=Product.objects.all()
    cart_item=cart.objects.all()
    categories=Category.objects.all()
    return render (request,'pages/cart.html',{'rows':rows})
   



    
def samsung (request):
    return render (request,'pages/Samsung.html',{
        'sam' : Product.objects.filter(category_id=1)
    })

def huawei (request):
    return render (request,'pages/Huawei.html',{
        'hwe' : Product.objects.filter(category_id=2)
        
    })

def Apple (request):
    return render (request,'pages/Apple.html',{
        'app' : Product.objects.filter(category_id=3)
    })

def product (request, productid):
    product= Product.objects.get(id=productid)
    cart_product_form = CartAddProductForm()
    return render (request,'pages/product.html',{'product':product,
    'cart_product_form':cart_product_form})

ecommercesite/cart/templates/cart/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">

  <title>Timups</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

</head>
  
  <tbody>
	<table>

		
			<h1>Your Shopping Cart</h1>
			<tr>
                <th>Cart info</th>
				<th>Product</th>
				<th>Quantity</th>
				<th>Remove</th>
				<th>Unit Price</th>
				<th>Price</th>
			</tr>
			</tbody>
		
		<body>
			{% if cart %}
				{% for item in cart %}
					{% with  product=item.product %}
					    <tr>
					    	<td>
					    		<a href="{{product.get_absolute_url}}">
					    			<img src="
                                    {{product.image.url}}"
					    			width="100px">
					    		</a>
					    	</td>
					    	<td>{{product.name}}</td>
					    	<td>
					    		<form method="post" action="{% url 'cart:cart_add' product.id %}">
					    			{% csrf_token %}
					    			{{item.update_quantity_form.quantity}}
					    			{{item.update_quantity_form.update}}
					    			<input type="submit" value="Update">
					    		</form>
					    	</td>
					    	<td>
					    		<a href="{% url 'cart:cart_remove' product.id%}">
					    			Remove
					    		</a>
					    	</td>
					    	<td>
					    		{{item.price}}
					    	</td>
					    	<td>
					    		{{item.total_price}}
					    	</td>
					    </tr>

					{% endwith %}
				{% endfor %}
			{% else %}
				<tr >
					<td colspan="4" style="width:100%;text-align:center;">there is no product !</td>
				</tr>
			{% endif %}
				<tr class="total">
					<td>
						Total
					</td>
					<td colspan="4"></td>
					<td class="num">${{cart.get_total_price}}</td>
				</tr>
		
	</table>
	<p class="text-right">
		<a href='http://127.0.0.1:8000/'>Continu shopping</a>
		
	</p>

<!-- end about section -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- popper js -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<!-- bootstrap js -->
<script src=" {% static 'js/bootstrap.js' %}"></script>
<!-- owl slider -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
</script>
<!-- custom js -->
<script src="{% static 'js/custom.js' %}"></script>
<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
<!-- End Google Map -->
</body>

</html>

ecommercesite/templates/pages/Apple.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">

  <title>Timups</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

</head>
<body>
<section class="shop_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Latest Watches
        </h2>
      </div>
      <div class="row">
       {%for item in app %}
        <div class="col-md-6 ">
            <div class="box">
              <a href="product/{{item.id}}">
                <div class="img-box">
                  <img src="{{item.image.url}}" alt="{{item.name}}">
                </div>
                <div class="detail-box">
                  <h6>
                    {{item.name}}
                  </h6>
                  <h6>
                    
                    <span>
                        {{item.Price}}
                    </span>
                  </h6>
                </div>
                <div class="new">
                  <span>
                    NEW
                  </span>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
          </div>
        </div>

          </div>
        </div>
      </div>
      
    </div>
  </section>
  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js'%}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js'%}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
  <!-- End Google Map -->
</body>
</html>

ecommercesite/templates/pages/Huawei.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">

  <title>Timups</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

</head>
<body>
<section class="shop_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Latest Watches
        </h2>
      </div>
      <div class="row">
       {%for item in hwe %}
        <div class="col-md-6 ">
            <div class="box">
              <a href="product/{{item.id}}">
                <div class="img-box">
                  <img src="{{item.image.url}}" alt="{{item.name}}">
                </div>
                <div class="detail-box">
                  <h6>
                    {{item.name}}
                  </h6>
                  <h6>
                    
                    <span>
                        {{item.Price}}
                    </span>
                  </h6>
                </div>
                <div class="new">
                  <span>
                    NEW
                  </span>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
          </div>
        </div>

          </div>
        </div>
      </div>
      
    </div>
  </section>
  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js'%}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js'%}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
  <!-- End Google Map -->
</body>
</html>

ecommercesite/templates/pages/Samsung.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">

  <title>Timups</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

</head>
<body>
<section class="shop_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Latest Watches
        </h2>
      </div>
      <div class="row">
       {%for item in sam %}
        <div class="col-md-6 ">
            <div class="box">
              <a href="product/{{item.id}}">
                <div class="img-box">
                  <img src="{{item.image.url}}" alt="{{item.name}}">
                </div>
                <div class="detail-box">
                  <h6>
                    {{item.name}}
                  </h6>
                  <h6>
                    
                    <span>
                        {{item.Price}}
                    </span>
                  </h6>
                </div>
                <div class="new">
                  <span>
                    NEW
                  </span>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
          </div>
        </div>

          </div>
        </div>
      </div>
      
    </div>
  </section>
  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js'%}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js'%}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
  <!-- End Google Map -->
</body>
</html>

ecommercesite/templates/pages/cart.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">

  <title>Cart</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

</head>
<body>

    <section class="about_section layout_padding">
        <div class="container  ">
          <div class="row">
            {%for item in cart1 %}
            <div class="col-md-6 col-lg-5 ">
              <div class="img-box">
                <img src="{{item.image.url}}" alt="{{item.name}}">
              </div>
            </div>
            <div class="col-md-6 col-lg-7">
              <div class="detail-box">
                <div class="heading_container">
                  <h2>
                    {{item.name}}
                  </h2>
                </div>
                <p>
                  {{item.description}}
                </p>
                <a href="">
                  Read More
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js'%}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js'%}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
  <!-- End Google Map -->
</body>
</html>

ecommercesite/templates/pages/product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">

  <title>Timups</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

</head>
<body>
<!-- about section -->

  <section class="about_section layout_padding">
    <div class="container  ">
      <div class="row">
      
        <div class="col-md-6 col-lg-5 ">
          <div class="img-box">
            <img src="{{product.image.url}}" alt="{{product.name}}">
          </div>
        </div>
        <div class="col-md-6 col-lg-7">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                {{product.name}}
              </h2>
            </div>
            <form method="post" action="{% url 'cart:cart_add' product.id %}">
              {% csrf_token %}
              {{cart_product_form}}
              <input type="submit" value="Add to cart">
            </form>
            <p>
              {{product.description}}
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src=" {% static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
  <!-- End Google Map -->
</body>
</html>